import { Inter } from 'next/font/google';
import './globals.css';
import AuthSessionProvider from '@/components/providers/AuthSessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthSessionProvider>
          <div className='h-screen overflow-hidden bg-black'>{children}</div>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
